### ISSUE TITLE
@MicronautTest(transactional = true) doesn't start transaction for GORM

### ISSUE THREAD

**Issue by matthew-long** [micronaut-projects/micronaut-groovy#39]
Repo showing the problem available at https://github.com/matthew-long/mn-gorm-tx
BookServiceSpec prints out that there is no transaction despite MicronautTest being configured for transactional behaviour.

I'd expect that when MicronautTest is configured for transactional and rollback behaviour that a transaction should be started before my test is invoked and that transaction rolled back after my test executes.

**Comment by sdelamo** [comment]
In Micronaut / GORM where you have a package where you place every GORM entity, I recommend tell Micronaut (both when you start the app and in the tests) where to scan:

Micronaut Groovy Docs:

> By default Micronaut will scan for entities relative to your Application class. If you wish to customize this specify additional packages via the ApplicationContextBuilder when starting your application.

That it is:

Instead of: 

```groovy
import io.micronaut.runtime.Micronaut
import groovy.transform.CompileStatic

@CompileStatic
class Application {
    static void main(String[] args) {
        Micronaut.run(Application)
    }
}
```

Use:

```groovy
import io.micronaut.runtime.Micronaut
import groovy.transform.CompileStatic

@CompileStatic
class Application {
    static void main(String[] args) {
        Micronaut.build(args)
                .packages("mn.gorm.tx")
                .mainClass(Application.class)
                .start()
    }
}
```

In tests where you start manually an `ApplicationContext` use: 

```groovy
class BookServiceSpec extends Specification {

    @AutoCleanup
    @Shared
    ApplicationContext applicationContext = ApplicationContext.build()
            .packages("mn.gorm.tx")
            .build()
            .start()

    @Shared
    @Subject
    BookService bookService = applicationContext.getBean(BookService)
```

In tests where you use `@MicronautTest` use: 

```groovy
@MicronautTest(packages = "mn.gorm.tx")
class MicronautTestBookServiceSpec extends Specification {

    @Inject
    BookService bookService
```

**Comment by sdelamo** [comment]
Your config: 

```
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
    # region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
dataSource:
  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
```

Should be something like: 

```
---
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
    # region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
dataSource:
  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password: ''
````

Unless you are using something like liquibase or flyway to create your database schema, you will need to tell hibernate to create for you: 

`hibernate.hbm2ddl.auto: update`
