### ISSUE TITLE
Cannot use DataSources default in application.yaml with hibernate gorm

### ISSUE THREAD

**Issue by jisikoff** [micronaut-projects/micronaut-groovy#9]
```yaml
dataSources:
  default:
    url: ...
```

doesn't seem to work in starting up a micronaut hibernate gorm project but using 
```yaml
dataSource:
  url: ...
```
does work
